### ISSUE TITLE
Updating the readme

### ISSUE THREAD

**Issue by dkyleward** [pbsag/outviz#17]
@gregmacfarlane 
I just got finished incorporating outviz into the NCSAM.  I'd like to add it as a use case example to the readme to help others build their project code.  The main problem I tackled was adding the pandoc binaries to the system path on the fly so that `rmarkdown::render()` could find it.

My main questions for you:
1. Are you ok with me adding this info to the readme.md?
2. Can I modify the master branch readme directly for this task, or do you want me to branch/pull?

**Comment by gregmacfarlane** [comment]
I guess I'm not sure why the pandoc binaries caused problems? That seems related to the user's R installation generally, and not to `outviz` explicitly. Maybe you can convince me otherwise...

If we do change something, branch/pull request, please.

**Comment by gregmacfarlane** [comment]
@dkyleward Pinging you to close this if it's not still an issue.

**Comment by rickdonnelly** [comment]
I've updated README.md, albeit without examples Kyle asked for. However, I'm thinking that we should spin those into vignettes rather than front page, so I'm going to close this issue. I admit that some improvements can still be made to this file, but I'm guessing they're minor. I don't know how to create vignettes and stitch them into the package, but will read on that this afternoon. I already have a few examples in RMarkdown that I should be able to quickly morph into vignettes.
